### ISSUE TITLE
nothing in clusterTools dir

### ISSUE THREAD

**Issue by olisteadman** [emzodls/clusterArch#8]
What's utils.py meant to find with this line? https://github.com/emzodls/clusterArch/blob/05b58ae285d3687d5c55fd2f1d4353b62d4e1ab9/utils.py#L27

I am trying to run `python main.py` and hitting a waterfall of dependency after dependency that needs installing. Having installed PyQt5 and Biopython I now need to resolve this error:

```
**(py3_for_cTools) oli@oli:~/clusterTools_via_GHub/clusterArch$** python main.py 
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    from utils import parseSeqFile,parseHMMfile,generateInputFasta,generateHMMdb,MakeBlastDB,runBLAST,runBLASTself,\
  File "/home/oli/clusterTools_via_GHub/clusterArch/utils.py", line 27, in <module>
    from clusterTools import clusterAnalysis
**ImportError: cannot import name 'clusterAnalysis'**

```

**Comment by emzodls** [comment]
clusterTools is another repo that you clone into the clusterArch folder, I wrote this first and I wasn't too familiar with github yet so I didn't set it up quite right.

**Comment by olisteadman** [comment]
Understood. Having found the [repo](https://github.com/emzodls/clusterTools) I cloned its contents into my local clusterTools dir so that it was no longer empty. The `utils.py` script then knew what it was looking for.
